### ISSUE TITLE
Latest version 0.2.1 is not yet available in pypi to use

### ISSUE THREAD

**Issue by anusajith** [vyos-contrib/pyvyos#4]
Hi Team, 
Since we wanted to use the functionality of multiple commands using pyvyos, why it is not still  available in the pypi registry?

![image](https://github.com/robertoberto/pyvyos/assets/88121157/b8509e90-c539-402e-b199-234980345e7d)

And please add examples how to use to handle lists of operations within a single payload functionality.

Can you please look into that.

Regards,
Anu

**Comment by TVKain** [comment]
Second this, the latest 0.2.1 has not been updated on the pypi registry

**Comment by robertoberto** [comment]
Hi, I will update it this week.

**Comment by robertoberto** [comment]
hello, while I don't update pip you can install 0.21:
`pip install git+https://github.com/robertoberto/pyvyos.git@8ae0b4f237eb20d9ad9f511154df8eb554bde398`

**Comment by robertoberto** [comment]
done https://pypi.org/project/pyvyos/ updated
